name: build-x64

on:
  push:
    branches:
      - x64-support
    paths-ignore:
      - LICENSE
      - README.md

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.containerImage }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-latest
          - linux-old
          - windows-latest

        sm_version:
          - "1.12"
          - "1.13"

        include:
          - meta_version: "1.12"
            meta_branch: "1.12-dev"

          - sm_version: "1.12"
            sm_branch: "1.12-dev"

          - sm_version: "1.13"
            sm_branch: "master"

          - platform: linux-latest
            os: ubuntu-latest
            os_short: linux
            ambuild_osargs: '--breakpad-upload'
            cc: 'clang'
            cxx: 'clang++'

          - platform: linux-old
            os: ubuntu-latest
            os_short: linux-old
            ambuild_osargs: ''
            cc: 'clang'
            cxx: 'clang++'
            containerImage: 'debian:bullseye'

          - platform: windows-latest
            os: windows-latest
            os_short: win
            ambuild_osargs: '--breakpad-upload'
    env:
      USER_BIN_PATH: ${{ github.workspace }}/bins
      BREAKPAD_SYMBOL_SERVER: 'http://crash.limetech.org/symbols/submit'
      IN_CONTAINER: ${{ matrix.containerImage != '' }}

    steps:
      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install Linux container dependencies
        if: startsWith(runner.os, 'Linux') && env.IN_CONTAINER == 'true'
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y install tzdata
          apt-get install -y --no-install-recommends \
            sudo \
            git \
            curl \
            wget \
            zstd \
            build-essential \
            software-properties-common

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.cc }} g++-multilib
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.cxx }}" >> $GITHUB_ENV

      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v3

      - name: Install Breakpad dump_syms (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p ${{ env.USER_BIN_PATH }}
          cd ${{ env.USER_BIN_PATH }}
          Invoke-WebRequest -Uri 'https://github.com/mozilla/dump_syms/releases/download/v2.3.7/dump_syms-x86_64-pc-windows-msvc.zip' -OutFile 'dump_syms-x86_64-pc-windows-msvc.zip'
          7z x dump_syms-x86_64-pc-windows-msvc.zip
          ls

      - name: Install Breakpad dump_syms (Linux)
        shell: bash
        if: runner.os == 'Linux'
        run: |
          mkdir -p ${{ env.USER_BIN_PATH }}
          cd ${{ env.USER_BIN_PATH }}
          wget https://github.com/mozilla/dump_syms/releases/download/v2.3.7/dump_syms-x86_64-unknown-linux-gnu.tar.xz
          tar -xvf dump_syms-x86_64-unknown-linux-gnu.tar.xz --strip-components 1
          ls

      - name: Update Path
        shell: bash
        run: |
          echo "${{ env.USER_BIN_PATH }}" >> "$GITHUB_PATH"

      - name: Getting SourceMod ${{ matrix.sm_version }}
        uses: actions/checkout@v7
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod-${{ matrix.sm_version }}
          submodules: recursive

      - name: Getting MM:Source ${{ matrix.meta_version }}
        uses: actions/checkout@v7
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.meta_branch }}
          path: metamod-${{ matrix.meta_version }}

      - name: Setup Python
        if: env.IN_CONTAINER == 'false'
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Setup Python (Container)
        if: startsWith( runner.os, 'Linux' ) && env.IN_CONTAINER == 'true'
        shell: bash
        run: |
          sudo apt-get install -y --no-install-recommends python3 python3-pip python-is-python3
          python3 -m pip install packaging
          python --version
          pip --version

      - name: Setup AMBuild
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Getting SDKs
        shell: bash
        run: |
          git clone --mirror https://github.com/alliedmodders/hl2sdk hl2sdk-proxy-repo
          sdks=(tf2 css hl2dm dods l4d2 l4d sdk2013 bms orangebox)
          for sdk in "${sdks[@]}"
          do
            git clone hl2sdk-proxy-repo -b $sdk hl2sdk-$sdk
          done

      - name: Getting own repository
        uses: actions/checkout@v7
        with:
          path: sourcetvmanager
          submodules: recursive

      - name: Compiling SourceTV Manager files
        working-directory: sourcetvmanager
        shell: bash
        run: |
          mkdir build
          cd build
          python ../configure.py --enable-optimize --sdks=present --sm-path="$GITHUB_WORKSPACE/sourcemod-${{ matrix.sm_version }}" --mms-path="$GITHUB_WORKSPACE/metamod-${{ matrix.meta_version }}" --targets x86,x86_64 ${{ matrix.ambuild_osargs }}
          ambuild

      - name: Uploading package
        uses: actions/upload-artifact@v7
        with:
          name: sourcetvmanager-sm${{ matrix.sm_version }}-${{ matrix.os_short }}
          path: sourcetvmanager/build/package

