name: build-x64

on:
  push:
    branches:
      - x64-support
    paths-ignore:
      - LICENSE
      - README.md

jobs:
  build:
    name: build with sm${{ matrix.sm_version }} on ${{ matrix.os_short }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.containerImage }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-latest
          - windows-latest

        sm_version:
          - "1.12"
          - "1.13"

        include:
          - meta_version: "1.12"
            meta_branch: "1.12-dev"

          - sm_version: "1.12"
            sm_branch: "1.12-dev"

          - sm_version: "1.13"
            sm_branch: "master"

          - platform: linux-latest
            os: ubuntu-latest
            os_short: linux
            ambuild_osargs: ''
            containerImage: ghcr.io/alliedmodders/build-containers/debian11-clang22:latest

          - platform: windows-latest
            os: windows-latest
            os_short: win
            ambuild_osargs: ''

          - sdks_to_fetch: 'tf2 css hl2dm dods l4d2 l4d sdk2013 bms orangebox'
            build_sdks: 'tf2,css,hl2dm,dods,l4d2,l4d,sdk2013,bms,orangebox'
            ambuild_target: 'x86,x86_64'

    env:
      USER_BIN_PATH: ${{ github.workspace }}/bins
      BREAKPAD_SYMBOL_SERVER: 'http://crash.limetech.org/symbols/submit'
      IN_CONTAINER: ${{ matrix.containerImage != '' }}

    steps:
      # Largely a workaround for issue where github.workspace doesn't match $GITHUB_WORKSPACE
      # in containerized jobs. See https://github.com/actions/runner/issues/2058
      - name: Resolve paths
        id: path_helper
        shell: bash
        run: |
          echo "dependencies=$GITHUB_WORKSPACE/dependencies" >> $GITHUB_OUTPUT
          echo "basedir=$GITHUB_WORKSPACE" >> $GITHUB_OUTPUT
          echo "userbins=$GITHUB_WORKSPACE/dependencies" >> $GITHUB_OUTPUT

      - name: Prepare env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Add msbuild to PATH (Windows)
        if: runner.os == 'Windows'
        uses: microsoft/setup-msbuild@v3

      - name: Install Breakpad dump_syms (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir -p ${{ steps.path_helper.outputs.userbins }}
          cd ${{ steps.path_helper.outputs.userbins }}
          Invoke-WebRequest -Uri 'https://github.com/mozilla/dump_syms/releases/download/v2.3.7/dump_syms-x86_64-pc-windows-msvc.zip' -OutFile 'dump_syms-x86_64-pc-windows-msvc.zip'
          7z x dump_syms-x86_64-pc-windows-msvc.zip
          ls
          echo "${{ steps.path_helper.outputs.userbins }}" >> "$GITHUB_PATH"

      - name: Getting SourceMod ${{ matrix.sm_version }}
        uses: actions/checkout@v7
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ matrix.sm_branch }}
          path: sourcemod
          submodules: recursive

      - name: Getting MM:Source ${{ matrix.meta_version }}
        uses: actions/checkout@v7
        with:
          repository: alliedmodders/metamod-source
          ref: ${{ matrix.meta_branch }}
          path: metamod

      - name: Setup Python
        if: runner.os == 'Windows'
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
  
      - name: Setup AMBuild
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install git+https://github.com/alliedmodders/ambuild

      - name: Fetch SDKs
        shell: bash
        run: |
          mkdir -p '${{ steps.path_helper.outputs.dependencies }}'
          cd '${{ steps.path_helper.outputs.dependencies }}'
          git clone --mirror https://github.com/alliedmodders/hl2sdk hl2sdk-proxy-repo
          sdks=(${{ matrix.sdks_to_fetch }})
          for sdk in "${sdks[@]}"
          do
            git clone hl2sdk-proxy-repo -b $sdk hl2sdk-$sdk
          done
          ls -lah

      - name: Getting own repository
        uses: actions/checkout@v7
        with:
          path: sourcetvmanager
          submodules: recursive

      - name: Compile Extension
        working-directory: sourcetvmanager
        shell: bash
        run: |
          mkdir build
          cd build
          python3 ../configure.py \
          --sdks=${{ matrix.build_sdks }} \
          --hl2sdk-root="${{ steps.path_helper.outputs.dependencies }}" \
          --sm-path="${{ steps.path_helper.outputs.basedir }}/sourcemod" \
          --mms-path="${{ steps.path_helper.outputs.basedir }}/metamod" \
          --enable-optimize \
          --targets "${{ matrix.ambuild_target }}" \
          --symbol-files ${{ matrix.ambuild_osargs }}
          ambuild

      - name: Uploading package
        uses: actions/upload-artifact@v7
        with:
          name: sourcetvmanager-sm${{ matrix.sm_version }}-${{ matrix.os_short }}
          path: sourcetvmanager/build/package

